/**
 * @file deadlineRescue.schema.ts
 *
 * Schema for Deadline Rescue Mode — an extension of Execution Intelligence.
 * 
 * Phase 9: Adaptive AI Replanning when user is significantly behind schedule.
 *
 * ── AGENT RESPONSIBILITY ─────────────────────────────────────────────
 *   ✓ Detects when user is unlikely to finish before deadline
 *   ✓ Generates compressed recovery strategy
 *   ✓ Recommends specific actions to recover
 *   ✓ Estimates recovery probability
 *   ✗ Does NOT regenerate full roadmap from scratch
 *   ✗ Does NOT modify original roadmap
 *   ✗ Does NOT change user's goal or deadline
 * ─────────────────────────────────────────────────────────────────────
 */

// ─── Rescue Mode Status ────────────────────────────────────────────────────────

/** Current state of deadline rescue system */
export type RescueStatus = 
  | 'not_needed'      // User is on track
  | 'monitoring'      // Slightly behind, but recoverable without rescue
  | 'active'          // Rescue mode activated
  | 'critical';       // Deadline extremely tight, may not be achievable

// ─── Recovery Action Types ─────────────────────────────────────────────────────

/** Specific actions the AI can recommend for recovery */
export type RecoveryActionType =
  | 'skip_optional'         // Skip optional modules
  | 'merge_weeks'           // Combine multiple weeks
  | 'compress_revision'     // Reduce revision time
  | 'increase_hours'        // Increase daily study hours
  | 'reduce_projects'       // Simplify or skip project work
  | 'focus_interview'       // Prioritize interview prep
  | 'focus_high_weight'     // Focus on high-weight DSA topics
  | 'defer_low_priority'    // Delay low-priority learning
  | 'escalate_mode';        // Switch to more aggressive execution mode

/** A single recovery action with rationale */
export interface RecoveryAction {
  type:        RecoveryActionType;
  description: string;   // Human-readable action (e.g., "Merge Week 3 + Week 4")
  impact:      string;   // Expected impact (e.g., "Saves 5 days")
  priority:    'high' | 'medium' | 'low';
}

// ─── Rescue Strategy ───────────────────────────────────────────────────────────

/**
 * The complete rescue strategy generated by the AI.
 * This is the recovery plan that replaces/supplements the original roadmap.
 */
export interface RescueStrategy {
  /** Why rescue mode was activated */
  reason:                  string;
  
  /** Current rescue status */
  status:                  RescueStatus;
  
  /** How many days behind schedule */
  daysBehind:              number;
  
  /** Ordered list of recovery actions */
  recoveryActions:         RecoveryAction[];
  
  /** Modules to skip completely */
  modulesToSkip:           string[];
  
  /** Week numbers to merge (e.g., [3, 4] means merge week 3 and 4) */
  weeksToMerge:            number[][];
  
  /** Topics to prioritize */
  topicsToPrioritize:      string[];
  
  /** Recommended new daily study hours */
  recommendedDailyHours:   number;
  
  /** Recommended new execution mode (if escalation needed) */
  recommendedExecutionMode?: string;
  
  /** Estimated completion date after rescue plan */
  estimatedCompletion:     string;  // ISO date
  
  /** Estimated days remaining after rescue plan */
  estimatedDaysRemaining:  number;
  
  /** Probability of completing before deadline (0-100) */
  recoveryProbability:     number;
  
  /** AI confidence in this rescue strategy (0-100) */
  confidence:              number;
  
  /** Motivational message encouraging the user */
  motivationalMessage:     string;
  
  /** ISO timestamp when this strategy was generated */
  computedAt:              string;
}

// ─── Rescue Response ───────────────────────────────────────────────────────────

export interface RescueResponse {
  success: boolean;
  data:    RescueStrategy;
}

// ─── Rescue Input ──────────────────────────────────────────────────────────────

/**
 * All data needed to generate a rescue strategy.
 * Assembled from existing repositories — no new data sources.
 */
export interface RescueInput {
  // Goal & Timeline
  currentGoal:             string;
  goalType:                string;
  deadline:                string;  // ISO date
  remainingDays:           number;
  
  // Roadmap Context
  roadmapVersion:          number;
  totalWeeks:              number;
  completedWeeks:          number;
  currentWeek:             number;
  remainingWeeks:          number;
  executionMode:           string;
  weeklyHours:             number;
  
  // Progress
  overallCompletionPct:    number;
  completedTasks:          number;
  totalTasks:              number;
  remainingHours:          number;
  
  // Current Pace
  currentPace:             number;   // weeks per week (actual)
  requiredPace:            number;   // weeks per week (needed to finish on time)
  
  // Goal Health & Intelligence
  goalHealthScore:         number;
  goalHealthLevel:         string;
  burnoutRisk:             string;
  deadlineRisk:            string;
  
  // ETA
  estimatedCompletionDate: string;  // ISO date from Goal Health
  estimatedDaysRemaining:  number;
  daysBehindSchedule:      number;  // negative if ahead, positive if behind
  
  // Streak & Consistency
  currentStreak:           number;
  consistencyRate:         number;
  
  // Topic Analysis (from Execution Intelligence)
  strongTopics:            string[];
  weakTopics:              string[];
  
  // Roadmap Modules (remaining only)
  remainingModules:        Array<{
    title:       string;
    weekNumber:  number;
    hours:       number;
    priority:    'high' | 'medium' | 'low';  // inferred from type
    type:        'learning' | 'revision' | 'project' | 'interview';
  }>;
}

// ─── Rescue History Entry ──────────────────────────────────────────────────────

/**
 * Immutable snapshot of a rescue activation.
 * Stored at users/{uid}/deadlineRescue/history/{timestamp}.
 */
export interface RescueHistoryEntry {
  status:                  RescueStatus;
  reason:                  string;
  daysBehind:              number;
  recoveryActions:         RecoveryAction[];
  estimatedCompletion:     string;
  recoveryProbability:     number;
  confidence:              number;
  activatedAt:             string;  // ISO timestamp
  roadmapVersion:          number;
  currentWeek:             number;
  overallCompletion:       number;
  recommendedDailyHours:   number;
}

// ─── Activation Criteria ───────────────────────────────────────────────────────

/**
 * Deterministic check to see if Rescue Mode should activate.
 * Called before making any AI request.
 */
export interface RescueActivationCheck {
  shouldActivate:    boolean;
  reason:            string;
  daysBehind:        number;
  estimatedOverrun:  number;  // days past deadline
}
