/**
 * @file goalHealth.schema.ts
 *
 * Schema for the Goal Health Score Agent.
 * Phase 7.1 additions:
 *   - HealthWeakness — structured weakness with reason + recommendation
 *   - HealthTrend    — delta + direction vs previous evaluation
 *   - GoalHealthHistoryEntry — immutable history document
 *
 * ── AGENT RESPONSIBILITY ─────────────────────────────────────────────
 *   ✓ Evaluates likelihood of roadmap completion using behavioral signals
 *   ✓ Returns structured weaknesses with per-item explanations
 *   ✗ Does NOT regenerate roadmap or analysis
 *   ✗ Does NOT modify progress data
 * ─────────────────────────────────────────────────────────────────────
 */

// ─── Health level ──────────────────────────────────────────────────────────────

export type HealthLevel = 'excellent' | 'healthy' | 'warning' | 'critical' | 'danger';

// ─── Burnout risk ──────────────────────────────────────────────────────────────

/** Burnout risk assessment based on consistency, missed tasks, and workload. */
export type BurnoutRisk = 'low' | 'medium' | 'high';

// ─── Deadline status (Phase 9) ─────────────────────────────────────────────────

/** Deadline status for quick visual indicator */
export type DeadlineStatus = 'on_track' | 'slightly_behind' | 'rescue_active' | 'critical';

// ─── Health trend ──────────────────────────────────────────────────────────────

/** Score change vs the previous evaluation. Computed by the service layer. */
export interface HealthTrend {
  /** Signed difference: positive = improved, negative = declined, 0 = stable. */
  delta:     number;
  direction: 'up' | 'down' | 'stable';
}

// ─── Structured weakness ──────────────────────────────────────────────────────

/**
 * A single weakness with an actionable explanation.
 * Replaces the plain string weakness format.
 */
export interface HealthWeakness {
  /** Short title shown as the bullet heading. */
  title:          string;
  /** One-sentence explanation of why this is a risk. */
  reason:         string;
  /** One-sentence actionable fix for this specific weakness. */
  recommendation: string;
}

// ─── GoalHealthScore ───────────────────────────────────────────────────────────

export interface GoalHealthScore {
  score:           number;
  level:           HealthLevel;
  summary:         string;
  /** Plain strings — unchanged from Phase 7. */
  strengths:       string[];
  /** Structured weaknesses with per-item explanations. */
  weaknesses:      HealthWeakness[];
  recommendations: string[];
  confidence:      number;
  computedAt:      string;
  /** Trend vs previous evaluation. Populated by service layer after AI call. */
  trend?:          HealthTrend;
  
  // ─── Phase 8.1 additions ────────────────────────────────────────────────────
  /** Burnout risk assessment. Generated by AI. */
  burnoutRisk:                BurnoutRisk;
  /** Estimated completion date as ISO date string. Computed deterministically. */
  estimatedCompletionDate:    string;
  /** Estimated days remaining until completion. Computed deterministically. */
  estimatedDaysRemaining:     number;
  /** Overall completion percentage (0-100). Computed deterministically. */
  overallCompletion:          number;
  /** Current streak count. Passed through from input. */
  currentStreak:              number;
  
  // ─── Phase 9 additions ──────────────────────────────────────────────────────
  /** Deadline status indicator (computed deterministically) */
  deadlineStatus?:            DeadlineStatus;
}

// ─── GoalHealthResponse ────────────────────────────────────────────────────────

export interface GoalHealthResponse {
  success: boolean;
  data:    GoalHealthScore;
}

// ─── GoalHealthHistoryEntry ───────────────────────────────────────────────────

/**
 * Immutable snapshot appended to history on every new evaluation.
 * Stored at users/{uid}/goalHealth/history/{timestamp}.
 */
export interface GoalHealthHistoryEntry {
  score:                   number;
  level:                   HealthLevel;
  confidence:              number;
  summary:                 string;
  strengths:               string[];
  weaknesses:              HealthWeakness[];
  recommendations:         string[];
  trend?:                  HealthTrend;
  evaluatedAt:             string;  // ISO timestamp — used as document id
  roadmapVersion:          number;
  streak:                  number;
  overallCompletionPct:    number;
  
  // ─── Phase 8.1 additions ────────────────────────────────────────────────────
  burnoutRisk:             BurnoutRisk;
  estimatedCompletionDate: string;
  estimatedDaysRemaining:  number;
}

// ─── GoalHealthInput ──────────────────────────────────────────────────────────

export interface GoalHealthInput {
  executionMode:         string;
  roadmapVersion:        number;
  totalWeeks:            number;
  completedWeeks:        number;
  overallCompletionPct:  number;
  remainingWeeks:        number;
  totalXP:               number;
  level:                 number;
  currentStreak:         number;
  longestStreak:         number;
  achievementCount:      number;
  consistencyRate:       number;
  replanCount:           number;
  streakActiveToday:     boolean;
  
  // ─── Phase 8.1 additions ────────────────────────────────────────────────────
  /** Deadline as ISO date string for ETA calculation. */
  deadline:              string;
  /** Average weekly completion rate (0-100%). For ETA calculation. */
  avgWeeklyProgress:     number;
  /** Total remaining estimated hours. For ETA calculation. */
  remainingHours:        number;
}
